package:
  name: matam
  version: "v1.2.0"

source:
  git_url: https://github.com/bonsai-team/matam.git
  git_tag: 7b1dd4a3beed73db1b3c0d5049c217c6d63441ea

requirements:
  build:
    - autoconf
    - zlib
    - google-sparsehash
    - bzip2
    - samtools >=1.0
    - python >=3.5
  run:
    - wget
    - libgcc-5 # [not osx]
    - zlib
    - python >=3.5
    - samtools >=1.0
    - rdptools
    - krona

test:
  commands:
    - matam_assembly.py -h

about:
  home: https://github.com/bonsai-team/matam
  license: AGPL-3.0
  license_file: LICENSE
