package:
  name: matam
  version: "{{ GIT_DESCRIBE_TAG }}"

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}

source:
  git_url: https://github.com/bonsai-team/matam.git

requirements:
  build:
    - autoconf
    - zlib
    - bzip2
    - samtools >=1.0
    - python >=3.5
  run:
    - wget
    - libgcc-5 # [not osx]
    - zlib
    - python >=3.5
    - samtools >=1.0
    - rdptools
    - krona
    - coreutils # Centos6 (otherwise sort --parallel is unrecognized)

test:
  commands:
    - matam_assembly.py -h

about:
  home: https://github.com/bonsai-team/matam
  license: AGPL-3.0
  license_file: LICENSE
